build: false
version: 0.6.{build}
platform:
  - x64

environment:
  matrix:
    - PYTHON: 3.7
      CONDA: "C:\\Miniconda36-x64"
    - PYTHON: 3.8
      CONDA: "C:\\Miniconda37-x64"

install:
  - set PATH=%CONDA%;%CONDA%\Library\bin;%CONDA%\bin;%CONDA%\Scripts;%PATH%
  - conda config --set always_yes yes
  - conda update conda
  - conda install python=%PYTHON% numpy scipy Cython sphinx pip --quiet
  - python -m pip install -U pip
  - pip install testflo
  - pip install git+https://github.com/hwangjt/sphinx_auto_embed.git
  - pip install -e . 
  - pip list
  - conda list

test_script:
  - testflo . -n 1
  - cd doc
  - sphinx_auto_embed
  - make html

notifications:
  - provider: GitHubPullRequest
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
