build: false

version: 0.1.{build}

platform:
  - x64

environment:
  matrix:
    - PYTHON: 3.6
    - PYTHON: 2.7

init:
  - set CONDA=Miniconda
  - if "%PYTHON%" == "3.6" (set CONDA=%CONDA%3)
  - if "%PLATFORM%" == "x64" (set CONDA=%CONDA%-x64)
  - echo %CONDA%
  - set PATH=C:\%CONDA%;C:\%CONDA%\Scripts;%PATH%
  - conda config --set always_yes yes
  # We need to do this first as other commands may not work with older versions of conda.
  - conda update conda
  - conda install Cython
  - IF "%ARCH%"=="64" (call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64)
  - IF "%ARCH%"=="64" (call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64)

install:
  - python -m pip install --upgrade pip
  - pip install numpy scipy
  # Grab testflo for running test, to ensure examples are run
  - pip install testflo
  - pip install git+https://github.com/hwangjt/sphinx_auto_embed.git
  - pip install -e .

test_script:
  - testflo . -n 1
  - cd doc
  - sphinx_auto_embed
  - make html
